### ISSUE TITLE
Can't attend in the second flow (non-english dataset)

### ISSUE THREAD

**Issue by blx0102** [NVIDIA/flowtron#32]
Hi there, thanks for your excellent work and sharing.
I'm training a non-English model from scratch, 2 speakers, both > 10h. I used the encoder and embedding layers from tacotron2, and started from n_flow=1, batch_size=1. 
After 1000k steps (~25 epochs), the model can produce not bad sound. The loss curve and attention plot are shown below.
![image](https://user-images.githubusercontent.com/17761044/84558879-b7330680-ad68-11ea-9da3-bc2a69dc9135.png)
![image](https://user-images.githubusercontent.com/17761044/84558886-c3b75f00-ad68-11ea-877f-726615686417.png)

So I add an extra flow and warmed-up from the 1 flow model. However, after 500k steps, there are only chaos in the second attention layer. The plots are shown below.
![image](https://user-images.githubusercontent.com/17761044/84558260-1e9a8780-ad64-11ea-972b-be3167c219ab.png)  ![image](https://user-images.githubusercontent.com/17761044/84558269-32de8480-ad64-11ea-9eb7-dfac86685852.png)

From your point, should I continue the 2 flows training? Or did I start the 2 flow training too early?

**Comment by KingStorm** [comment]
Same issue here, I used on non-English speaker dataset > 10h, and used the fixed token/speaker embedding from multi-speaker tacotron2, and start training with n_flow=1. (I did not reuse the text encoder from tacotron2, probably I should also apply this strategy)

The model is able to attend for the first flow, but cannot learn the second flow. I am wondering if it would be easier when we set sigma to 0 as a warmstarting training strategy, so that the simple Gaussian distribution becomes dirac delta and there will be no random factors affecting.

**Comment by rafaelvalle** [comment]
@blx0102 when you started training the 2nd step of flow, did you set [include_layers](https://github.com/NVIDIA/flowtron/blob/master/config.json#L13) to `null`?

**Comment by blx0102** [comment]
@rafaelvalle Thanks for your reply.
1. Yes, I did set include_layers to None while started the 2nd step of flow
2. Attention almost always has the bias on the last token. Bias can be seen from about 50k-steps
3. Yes, I trained with 2 speakers, and embedding dim remains 128

**Comment by youmebangbang** [comment]
I too am experiencing the same issue. I began training from the nvidia model with my own 20hr single speaker dataset. I ignored the speaker layer. Trained to 1.3mil and attention is good and inference sounds decent. I used 1e-4 then 1e-5 learning rates.  Then I tried on flow 2 with warm start from previous run checkpoint, include layers to none, with both 1e-4 and 1e-5 rates and still same horizontal lines in attention that eventually turn most blank screen.

**Comment by jhjungCode** [comment]
I think warmstart has a error. it havn't a parameter for include_layers.
_________________________________________________original
    if warmstart_checkpoint_path != "":
        model = warmstart(warmstart_checkpoint_path, model)
_________________________________________________
_________________________________________________currect
    if warmstart_checkpoint_path != "":
        model = warmstart(warmstart_checkpoint_path, model, include_layers)
_________________________________________________

**Comment by rafaelvalle** [comment]
@jhjungCode nice find! this does not solve their issue but confirms that they were using `include_layers=None`.

**Comment by rafaelvalle** [comment]
@blx0102 @youmebangbang please try resuming from a 1 step of flow checkpoint that does not have a bias on the attention maps.
@youmebangbang can you show similar plots to the ones we have here?

**Comment by youmebangbang** [comment]
@rafaelvalle I apologize I do not understand, how does one resume checkpoint without bias on the attention?

**Comment by rafaelvalle** [comment]
Do you have a checkpoint in which the model has good attention in no bias?

**Comment by altsoph** [comment]
@blx0102 BTW, were you able to solve this issue? I'm experiencing the same kind of problems (even on the original LJS data)

**Comment by blx0102** [comment]
@altsoph Yes my issue has been solved. I retrained a better taco2 model for warmstart, which has no bias in the attention plot. For English training, maybe you could try to warmstart with the official pretrained taco2 model.

**Comment by altsoph** [comment]
@blx0102 okay, thanks! I'm going to train it for Russian, but decided to check how it works from scratch on English first. It didn't so I suspected there is some trick :)

**Comment by rafaelvalle** [comment]
And make sure you're training the steps of flow progressively, that is, train a Flowtron with 1 step of flow until it's able to attend to the text. Once this happens, use this model to warmstart a Flowtron with 2 steps of flow and so on.

**Comment by altsoph** [comment]
@rafaelvalle I trained a 1-flow model to attend without problems, but still can't recover the attention after warmstart with 2 flows. I'll keep trying, thanks :)

**Comment by rafaelvalle** [comment]
@altsoph When you `warmstart_checkpoint_path` from the Flowtron with 1 step of flow that is able to attend, make sure you set [include_layers](https://github.com/NVIDIA/flowtron/blob/master/config.json#L13) to `null` otherwise you [won't load all weights](https://github.com/NVIDIA/flowtron/blob/master/train.py#L88) from the pre-trained model

**Comment by tunnermann** [comment]
Hello, first, thanks for your work. As I really like waveglow I'm excited about flowtron. I'm having a similar problem while training flowtron in my brazilian portuguese dataset. For 1 flow I can get decent attention alignments, with quite good synthesized speech. Here is one allignment map:

![sid2_sigma0 5_attnlayer0](https://user-images.githubusercontent.com/9556214/88209653-6812a800-cc29-11ea-8461-a4096bd7649d.png)

When I try to use it to warmstart a 2 flow model the attention on the first flow gets worse over time and the attention map for the second flow is just noise.

I'm setting include_layers to null, using 3 speakers with 10 hours each, tried with and without speaker embeddings, I'm not using phoneme representations, so I set p_arpabet to 0.0.

So, do you have some suggestions of steps I might take to train the model?

Another question I have is about batch_size, I see people using only batch_size of 1, any reason for that? Should I try different batch sizes?

**Comment by rafaelvalle** [comment]
@tunnermann can you share the config.json file you're using to train the 2nd flow?

**Comment by tunnermann** [comment]
Thanks for your reply, here it is:

{

    "train_config": {
        "output_directory": "outdir",
        "epochs": 10000000,
        "learning_rate": 1e-4,
        "weight_decay": 1e-6,
        "sigma": 1.0,
        "iters_per_checkpoint": 10000,
        "batch_size": 1,
        "seed": 1234,
        "checkpoint_path": "",
	    "ignore_layers": [],
        "include_layers": [],
        "warmstart_checkpoint_path": "models/model_1_flow_3_speakers_2",
	    "with_tensorboard": true,
        "fp16_run": true 
    },

    "data_config": {
        "training_files": "../dataset/metadata_flowtron.csv", 
        "validation_files": "../dataset/JC/metadata_flowtron_val.csv",
        "text_cleaners": ["basic_cleaners"],
        "p_arpabet": 0.0,
        "cmudict_path": "data/cmudict_dictionary",
        "sampling_rate": 22050,
        "filter_length": 1024,
        "hop_length": 256,
        "win_length": 1024,
        "mel_fmin": 0.0,
        "mel_fmax": 8000.0,
        "max_wav_value": 32768.0
    },

    "dist_config": {
        "dist_backend": "nccl",
        "dist_url": "tcp://localhost:54321"
    },
    
    "model_config": {
        "n_speakers": 3,
        "n_speaker_dim": 128,
        "n_text": 185,
        "n_text_dim": 512,
        "n_flows": 2,
        "n_mel_channels": 80,
        "n_attn_channels": 640,
        "n_hidden": 1024,
        "n_lstm_layers": 2,
        "mel_encoder_n_hidden": 512,
        "n_components": 0,
        "mean_scale": 0.0,
        "fixed_gaussian": true,
        "dummy_speaker_embedding": false,
        "use_gate_layer": true
    } 
}

**Comment by rafaelvalle** [comment]
Can you share the loss curves?

**Comment by tunnermann** [comment]
Sure, here are the loss curves:
1-Flow:
![Captura de tela de 2020-07-23 04-32-59](https://user-images.githubusercontent.com/9556214/88277707-88894380-ccb7-11ea-9ef2-598a05d00729.png)

2-Flow(I lost the one with more steps, but it looks similar):
![Captura de tela de 2020-07-23 04-52-08](https://user-images.githubusercontent.com/9556214/88278847-73151900-ccb9-11ea-808d-c995eb63e452.png)

No, I can't find any 1 step model that does not attend to the first token.

Another thing I noticed now is that I may be doing something wrong in inference with 2 flows. In tensorboard images the attention in attention_weights_0 is still good(attention_weights_1 is noise), but when I do inference it is not, like in the image bellow(sid1_sigma05_attnlayer1.png):
![sid1_sigma0 5_attnlayer1](https://user-images.githubusercontent.com/9556214/88279420-693fe580-ccba-11ea-9ae7-e87dcb8628d1.png)

**Comment by rafaelvalle** [comment]
What about the validation loss?

**Comment by tunnermann** [comment]
Here you go, 1-flow:

![Captura de tela de 2020-07-23 11-07-25](https://user-images.githubusercontent.com/9556214/88316313-010af700-ccee-11ea-9a20-8207272e9e8c.png)

2-flow:

![Captura de tela de 2020-07-23 11-02-22](https://user-images.githubusercontent.com/9556214/88316345-108a4000-ccee-11ea-934b-dff79952eb64.png)

Inference keeps getting worse the more I train, even though the image of the attention in tensorboard does not change much.

**Comment by rafaelvalle** [comment]
Keep training while the validation loss is going down.

**Comment by tunnermann** [comment]
Thanks for your help, just knowing there is nothing obviously wrong with what I'm doing already clear things for me. I will continue with this training as you suggested, then I will try generating a 1-flow model without the first token attention problem, and if it is not solved yet I will try using phonemes to help with learning attention.

**Comment by rafaelvalle** [comment]
Yes, the attention map on the first flow should remain correct while the attention map on the second flow improves and the validation loss goes down. Let us know when you're able to get good results.

**Comment by zjFFFFFF** [comment]
when i train a 2-flow model based on 1-flow model.I set include_layers to null. I get this error. 
The number of speaker is 1.

Warm starting model outdir_preprocess_sr22050/model_2750000.pt
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 188, in train
    model = warmstart(warmstart_checkpoint_path, model, include_layers)
  File "train.py", line 96, in warmstart
    if pretrained_dict['speaker_embedding.weight'].shape != model_dict['speaker_embedding.weight'].shape:
KeyError: 'speaker_embedding.weight'

Can you help me.
